ECC-Project-Group/ExeterCourseMap

pages/course/[id].tsx

On every page with a prerequisite flowchart, there is now a button that allows the user to get more prerequisites down the tree, and these new prerequisites will render on the flowchart.

Add render more prereqs button to course flowchart

---

components/header.tsx
package-lock.json
package.json
pages/_app.tsx
pages/api/auth/[...nextauth].ts

Any frontend devs, please make this look less ugly. A github third party OAuth has been done, if you need an env message me for one. I will continue to work on custom login and/or outlook login.

Added authentication... Work required on styling

---

pages/api/auth/[...nextauth].ts

May all frontend devs unite to fix this ugly monstrosity.

Added outlook authentication

---

components/header.tsx
package-lock.json
package.json
pages/api/auth/[...nextauth].ts

Users can sign in with Exeter email, Gmail, or any email with a link.

Implement full authentication flow

---

lib/course_colors.tsx
lib/courses.ts
pages/_app.tsx
pages/api/course_info/[id].tsx
pages/api/prereqs/[id].tsx
pages/course/[id].tsx
pages/courses.tsx
pages/map.tsx
pages/maps.tsx
pages/maps/[id].tsx

Why: Previous commits had numerous warnings and some errors when building,
this commit fixes the errors and reduces the warnings.
How: Used npm run test-all to check format, lint, check types, and
eventually check build. Ran all the tests and applied fixes until no
more errors appeared
Tags: Refactor, Typings, Building, Compiling

Add Type Annotations, Refactor Code Style, Fix Build

---

lib/gtag.ts
package-lock.json
package.json
pages/_app.tsx
pages/course/[id].tsx

See commit messages for more info

Added Google Analytics with Basic Functions

---

lib/generateLayout.tsx
package-lock.json
package.json
pages/_app.tsx
pages/courses.tsx
pages/index.tsx
pages/map.tsx
pages/maps.tsx

This commit was split into two commits because I forgot to git pull upstream main before committing

Add subject search to course page + minor fixes

---

lib/gtag.ts
package-lock.json

Why: A previous commit caused a structural error in package-lock.json.
This commit fixes the issue and also patches a previous issue when the
environment variable was renamed, causing Google Analytics to not
function properly.
How: Added three closing braces to the end of package-lock.json, also
modified the name of the environment variable in lib/gtag.ts
Tags: Bugfix, package-lock.json, Google Analytics

Bugfix for Google Analytics and package-lock.json

---

pages/course/[id].tsx
pages/maps/[id].tsx

How: Parsed prereq and coreq strings due to their structure, and added
them conditionally and grammatically to the popups and the descriptions
of each course
Tags: Prereq, Coreq, Description, Popup

Added Prereq, Coreq, and Eligibility Descriptions

---

data/courses.json
pages/course/[id].tsx
pages/maps/[id].tsx
types.ts

How: Re-parsed data/courses.json to include the COI description content,
and added them along with other records, following a similar code style.
Tags: Forgot to Add :(

Added COI Description String to All Course and Map

---

pages/courses.tsx

Added drop shadow and added highlight to search bar on hover + focus.
Creating a PR now to solve potential merge conflict with #65

Slight visual adjustments to /courses

---

lib/generateLayout.tsx

Add transition property to course map nodes

---

pages/about.tsx
pages/course/[id].tsx

Specifically no-unused-vars in about.tsx and unused icon import in /course/[id]

Fix linting errors

---

pages/index.tsx

Test PR 2-please ignore

---

components/courseInfoPopup.tsx
components/expandableText.tsx
components/header.tsx
pages/_document.tsx
pages/course/[id].tsx
pages/courses.tsx
pages/index.tsx
pages/maps.tsx
pages/maps/[id].tsx
tailwind.config.js

Mostly all pages and components have been given a dark-mode facelift!

Add customized dark mode

---

components/header.tsx
components/useScrollBlock.tsx
pages/_document.tsx
pages/index.tsx

Sign-in/out modal is centered on mobile devices, also adds buttons to close modal (is not clear the user must tap outside to close). Also added cool animations.

Mobile sign-in/out experience overhaul

---

components/courseInfoPopup.tsx
pages/course/[id].tsx
pages/courses.tsx
pages/index.tsx
pages/maps.tsx
public/graph.svg

VERY COOL AND DESCRIPTIVE PR DESCRIPTION

Fix Safari visual inconsistencies and added new call to action section on index

---

pages/courses.tsx

Fixed lint error when upgrading to React 18

---

pages/index.tsx

It might fry your GPU but it's all worth it in the end
Updated shadows + reflections

Homepage 3D facelift

---

pages/course/[id].tsx
pages/maps/[id].tsx

Also removed one case of redundant closing bracket.

Removed redundant JSON field names
